services:
  - type: web
    name: offline-attendance-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        sync: false
